# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ThumbnailHistoryHalfNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ThumbnailHistoryHalfNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsThumbnailHistoryHalfNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ThumbnailHistoryHalfNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ThumbnailHistoryHalfNode
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ThumbnailHistoryHalfNode
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # ThumbnailHistoryHalfNode
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # ThumbnailHistoryHalfNode
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ThumbnailHistoryHalfNode
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def ThumbnailHistoryHalfNodeStart(builder):
    builder.StartObject(2)

def Start(builder):
    ThumbnailHistoryHalfNodeStart(builder)

def ThumbnailHistoryHalfNodeAddId(builder, id):
    builder.PrependInt64Slot(0, id, 0)

def AddId(builder, id):
    ThumbnailHistoryHalfNodeAddId(builder, id)

def ThumbnailHistoryHalfNodeAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder, data):
    ThumbnailHistoryHalfNodeAddData(builder, data)

def ThumbnailHistoryHalfNodeStartDataVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartDataVector(builder, numElems):
    return ThumbnailHistoryHalfNodeStartDataVector(builder, numElems)

def ThumbnailHistoryHalfNodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return ThumbnailHistoryHalfNodeEnd(builder)
